DROP TABLE PEOPLE IF EXISTS;

CREATE TABLE IF NOT EXISTS PEOPLE (
    PEOPLE_ID         INTEGER     NOT NULL AUTO_INCREMENT,
    FIRST_NAME        VARCHAR(50) NOT NULL,
    MIDDLE_NAME       VARCHAR(50) NULL,
    LAST_NAME         VARCHAR(50) NOT NULL,
    BIRTHDAY          VARCHAR(50) NULL,
    FAVORITE_COLOR    VARCHAR(50) NULL,
    BIRTH_LOCATION    VARCHAR(50) NULL,
    MOTHER_NAME       VARCHAR(50) NULL,
    FATHER_NAME       VARCHAR(50) NULL,
    MARITAL_STATUS    VARCHAR(50) NULL,
    GENDER            VARCHAR(50) NULL,
    VEGETARIAN_VEGAN  VARCHAR(50) NULL,

    PRIMARY KEY(PEOPLE_ID)
);